apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: notes-hpa-autoscaler
  namespace: hpa-testing
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notes-deployment-hpa
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 20
