apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-deployment
  labels:
    app: notes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
      - name: notes
       # image: nginx:latest #registry.prashanthgr.private:5000/notes:v1.0.1
        image: registry.prashanthgr.private:5000/notes:v1.0.1
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: notes-service
spec:
  type: NodePort
  ports:
  - nodePort: 30154
    port: 800
    targetPort: 80
    protocol: TCP
#  type: LoadBalancer
#  loadBalancerIP: "192.168.1.109"
  selector:
    app: notes

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notes-ingress
spec:
  rules:
  - host: www.prashanthgnotes.com
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: notes-service
            port:
              number: 800
  ingressClassName: nginx
