apiVersion: v1
kind: Service
metadata:
  name: notes-blue-green-service
spec:
  type: NodePort
  ports:
  - nodePort: 32000
    port: 800
    targetPort: 80
    port: 810
    targetPort: 80
    protocol: TCP
#  type: LoadBalancer
#  loadBalancerIP: "192.168.1.109"
  selector:
    role: target-role

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notes-blue-green-deply-ingress
spec:
  rules:
  - host: www.prashanthgnotes.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: notes-blue-green-service
            port:
              number: 800
              number: 810
  ingressClassName: nginx
